export enum ActionType {
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    CREATE_ORDER = "CREATE_ORDER",
    CLEAR_ORDER = "CLEAR_ORDER",
    FETCH_ORDERS = "FETCH_ORDERS"
}